stages:
  phonemize:
    cmd: python src/phonemize.py --inp data/manifests/en/clean.jsonl --out 
      data/manifests/en/phon.jsonl
    deps:
    - data/manifests/en/clean.jsonl
    - src/phonemize.py
    outs:
    - data/manifests/en/phon.jsonl
  noise10:
    cmd: python src/add_noise.py --inp data/manifests/en/phon.jsonl --out 
      data/manifests/en/noisy_10.jsonl --noise data/noise/white.wav --snr 10
    deps:
    - data/manifests/en/phon.jsonl
    - data/noise/white.wav
    - src/add_noise.py
    outs:
    - data/manifests/en/noisy_10.jsonl
  eval10:
    cmd: python src/eval_per.py --inp data/manifests/en/hyp_10.jsonl --out 
      metrics/per_10.json
    deps:
    - data/manifests/en/hyp_10.jsonl
    - src/eval_per.py
    outs:
    - metrics/per_10.json
  plot10:
    cmd: python src/plot_per.py --inp metrics/per_10.json --out 
      figs/per_vs_noise.png --snr 10
    deps:
    - metrics/per_10.json
    - src/plot_per.py
    outs:
    - figs/per_vs_noise.png
